# Generated by Django 2.0.6 on 2018-06-20 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_m3', models.IntegerField()),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='freight.Location')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='freight.Location')),
            ],
        ),
    ]
