# Generated by Django 2.0.6 on 2018-08-07 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0002_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('type', models.SmallIntegerField(choices=[(0, 'Character'), (1, 'Corporation'), (2, 'Alliance')])),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='acceptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_contracts', to='freight.Entity'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_contracts', to='freight.Entity'),
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
